server:
  port: 9960

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  redis:
    database: 0
    password:
    port: 6379


ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000

