server:
  port: 9561   #9561-9580

eureka:
  client:
    service-url:
      defaultZone: http://172.18.84.32:8761/eureka/
spring:
  application:
    name: user-service
  datasource:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  发发发发发发发发发发发发发发发发发发发发发发发发发发发发发发发发发发发发发发发发发发发发发发发发发发发发发发发发发发发发发发发发发VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tesco?useUnicode=true&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  devtools:
    restart:
      enabled: true

  redis:
    database: 0
    password:
    port: 6379
##文件中取消模板文件引擎
#  thymeleaf:
#    cache: false
#




mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zkdj.userservice.domain
  configuration:
    map-underscore-to-camel-case: true
#
#pay-service-1:
#  ribbon:
#    ConnectTimeout: 1000
#    ReadTimeout: 2000
#    okToRetryOnAllOperations: true
#
#    MaxAutoRetries: 1
#    MaxAutoRetriesNextServer: 2
#    http:
#      client:
#        enabled: true
#
