server:
  port: 9561   #9561-9580

eureka:
  client:
    service-url:
      defaultZone: http://172.18.84.32:8761/eureka/

spring:
  mail:
    host: smtp.163.com
    username: mgr15878571440@163.com
    password: PZDASTDSYISJFIQC

  application:
    name: user-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tesco?useUnicode=true&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

  devtools:
    restart:
      enabled: true

  redis:
    database: 0
    password:
    port: 6379
  cache:
    type: redis
#  mail:
#    host: stmp.163.com
#    username: CC1316886229@163.com
#    password: JYTPNGIRUJZYGBXL

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zkdj.userservice.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#call other service
#my-stock-service:
#  ribbon:
#    ConnectTimeout: 100
#    ReadTimeout: 200
#    OkToRetryOnAllOperations: true
#    MaxAutoRetries: 1
#    MaxAutoRetriesNextServer: 2
#    http:
#      client:
#        enabled: true
#



feign:
  hystrix:
    enabled: true

#
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 2000
#  feign整合ribbon  feign里面也有一个超时设置啥
#要想测试hystrix的超时时间 需要设置 ribbon的超时间大于 hystrix的超时时间
