
server:
  port: 9562   #9561-9580

eureka:
  client:
    service-url:
      defaultZone: http://172.18.84.32:8761/eureka/
spring:
  application:
    name: pay-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tesco?useUnicode=true&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  devtools:
    restart:
      enabled: true

  redis:
    database: 0
    password:
    port: 6379

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zkdj.userservice.domain
  configuration:
    map-underscore-to-camel-case: true

user-service-1:
  ribbon:
    ConnectTimeout: 1000
    ReadTimeout: 2000
    okToRetryOnAllOperations: true

    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2
    http:
      client:
        enabled: true

