#  9541-9560
server:
  port: 9548

eureka:
  client:
    service-url:
      defaultZone: http://172.18.84.32:8761/eureka/

spring:
  application:
    name: my-cart-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tesco?useUnicode=true&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

  devtools:
    restart:
      enabled: true

  redis:
    database: 2
    password:
    port: 9545
  cache:
    type: redis

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.legou.cart.domain
  configuration:
    map-underscore-to-camel-case: true



#call other service
my-cart-service:
  ribbon:
    ConnectTimeout: 3000
    ReadTimeout: 5000
    okToRetryOnAllOperations: true

    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2
    http:
      client:
        enabled: true



feign:
  hystrix:
    enabled: true


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
            # setting time out



