#  9541-9560
server:
  port: 9543

eureka:
  client:
    service-url:
      defaultZone: http://172.18.84.32:8761/eureka/

spring:
  application:
    name: my-comment-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tesco?useUnicode=true&serverTimezone=UTC
    username: root
    password: 123456


  devtools:
    restart:
      enabled: true

  redis:
    database: 2
    password:
    port: 9543
  cache:
    type: redis

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.legou.comment.domain
  configuration:
    map-underscore-to-camel-case: true



#call other service
my-goods-service:
 ribbon:
   ConnectTimeout: 3000
   ReadTimeout: 5000
   okToRetryOnAllOperations: true

   MaxAutoRetries: 1
   MaxAutoRetriesNextServer: 2
   http:
     client:
       enabled: true



feign:
  hystrix:
    enabled: true


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
            # setting time out



